apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      volumes:
        - name: shared-project
          persistentVolumeClaim:
            claimName: project-claim
      containers:
        - name: project
          image: chanioxaris/devops-k8s-mooc-project
          volumeMounts:
            - name: shared-project
              mountPath: /usr/src/app/files