apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainapp
  template:
    metadata:
      labels:
        app: mainapp
    spec:
      volumes:
        - name: shared-mainapp
          persistentVolumeClaim:
            claimName: mainapp-claim
      containers:
        - name: mainapp-generator
          image: chanioxaris/devops-k8s-mooc-main-app-generator
          volumeMounts:
            - name: shared-mainapp
              mountPath: /usr/src/app/files
        - name: mainapp-server
          image: chanioxaris/devops-k8s-mooc-main-app-server
          volumeMounts:
            - name: shared-mainapp
              mountPath: /usr/src/app/files